### ISSUE TITLE
Integrate DSMR smart meter 

### ISSUE THREAD

**Issue by Ruben9477** [nmakel/solaredge_meterproxy#11]
Would it be possible to integrate my P1 DSMR5 meter as energy meter? For example with a plugin from [https://github.com/dsmrreader/dsmr-reader](url)

**Comment by nmakel** [comment]
I'm not familiar with the DSMR world, and don't have a suitable energy meter to test this with. A quick look at dsmr-reader suggests to me that reading from its influxdb backend is the quickest way of getting solaredge_meterproxy to do what you want.
