### ISSUE TITLE
ModuleNotFoundError: No module named 'pymodbus.server.sync'

### ISSUE THREAD

**Issue by elngejw** [nmakel/solaredge_meterproxy#24]
Hi all,

I installed all requirements, but I still get the following error:

_openhabian@rpizero:~/shared/solaredge_meterproxy $ python3 semp-rtu.py
Traceback (most recent call last):
  File "/home/openhabian/shared/solaredge_meterproxy/semp-rtu.py", line 11, in <module>
    from pymodbus.server.sync import StartSerialServer
**ModuleNotFoundError: No module named 'pymodbus.server.sync'**_

Anybody knows where to look for?

Many thanks for your support!!

**Comment by nmakel** [comment]
You're using an outdated `semp-rtu.py`. Grab the latest from github and you should be good to go.

**Comment by elngejw** [comment]
Many thanks!!
