### ISSUE TITLE
QUESTION: MQTT integration

### ISSUE THREAD

**Issue by Maikel-K** [nmakel/solaredge_meterproxy#6]
Hi Niels,

Its me again... hope you don't mind.

Would it be possible to send all the data of the SDM to MQTT too?
The gateway im using can accept 5 connections but I don't want the one script to get in the way of the other script.

As we are already recieving info from the SDM and pushing it to the inverter would it also be possible to push the data to MQTT in the same go?

**Comment by nmakel** [comment]
As I said in issue #2, where you also requested this: it is possible to have multiple processes talk to the same Modbus device through those gateways. While you should be able to modify the sdm120.py or sdm630.py script in /devices/, you should probably find software which is made for that purpose. For example, you can use [sdm_modbus](https://github.com/nmakel/sdm_modbus) and add the MQTT functionality to the example script.
